trigger:
  branches:
    include:
    - main
    - develop
    - feature/*
    - bug/*

pr:
  branches:
    include:
    - main
    - develop

# Pool build
pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: devops
    endpoint: Application
    type: github
    name: LocTaRND/azure-devops-template
    ref: azuredevops

variables:
  - group: demo_var
  - group: be

stages:
  - template: templates/dotnet/build.yml@devops